/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockMessageTransmitter,
  MockMessageTransmitterInterface,
} from "../../../mocks/MockMessageTransmitter.sol/MockMessageTransmitter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountToMint",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "amountToMint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "receiveMessage",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "recipient",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newAmount",
        type: "uint256",
      },
    ],
    name: "setAmountToMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newRecipient",
        type: "address",
      },
    ],
    name: "setRecipient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a034609857601f61036238819003918201601f19168301916001600160401b03831184841017609d5780849260609460405283398101031260985760428160b3565b906040604f6020830160b3565b910151608092909252600080546001600160a01b0319166001600160a01b0390921691909117905560015560405161029b90816100c78239608051818181607801526101870152f35b600080fd5b634e487b7160e01b600052604160045260246000fd5b51906001600160a01b038216820360985756fe608080604052600436101561001357600080fd5b600090813560e01c9081633bbed4a01461022257816357ecfd281461010a5750806366d003ac146100e3578063e5d61eef146100c8578063e6fb1fb4146100aa5763fc0c546a1461006357600080fd5b346100a757806003193601126100a7576040517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b80fd5b50346100a757806003193601126100a7576020600154604051908152f35b50346100a75760203660031901126100a75760043560015580f35b50346100a757806003193601126100a757546040516001600160a01b039091168152602090f35b90503461021e57604036600319011261021e5760043567ffffffffffffffff811161021a5761013d90369060040161025b565b505060243567ffffffffffffffff811161021a5761015f90369060040161025b565b505060015480610175575b602060405160018152f35b825483916001600160a01b03918216917f00000000000000000000000000000000000000000000000000000000000000001690813b15610216578360449286949285936340c10f1960e01b8552600485015260248401525af1801561020b576101df575b8061016a565b67ffffffffffffffff81116101f757604052386101d9565b634e487b7160e01b82526041600452602482fd5b6040513d84823e3d90fd5b8380fd5b8280fd5b5080fd5b82346100a75760203660031901126100a7576004356001600160a01b0381169081900361021e5781546001600160a01b03191617815580f35b9181601f840112156102895782359167ffffffffffffffff8311610289576020838186019501011161028957565b600080fdfea164736f6c634300081a000a";

type MockMessageTransmitterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockMessageTransmitterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockMessageTransmitter__factory extends ContractFactory {
  constructor(...args: MockMessageTransmitterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _token: AddressLike,
    _recipient: AddressLike,
    _amountToMint: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      _token,
      _recipient,
      _amountToMint,
      overrides || {}
    );
  }
  override deploy(
    _token: AddressLike,
    _recipient: AddressLike,
    _amountToMint: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(
      _token,
      _recipient,
      _amountToMint,
      overrides || {}
    ) as Promise<
      MockMessageTransmitter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockMessageTransmitter__factory {
    return super.connect(runner) as MockMessageTransmitter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockMessageTransmitterInterface {
    return new Interface(_abi) as MockMessageTransmitterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockMessageTransmitter {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockMessageTransmitter;
  }
}
