/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockMessageTransmitterSol from "./MockMessageTransmitter.sol";
export type { mockMessageTransmitterSol };
export type { MockERC20 } from "./MockERC20";
