/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EthCctpReceiveProxyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "manager"
      | "receiveMessageAndForward"
      | "rescue_transfer"
      | "setAdmin"
      | "setManager"
      | "setTransferTo"
      | "transferTo"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminUpdated"
      | "ManagerUpdated"
      | "MessageReceivedAndForwarded"
      | "RescueTransfer"
      | "TransferToUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiveMessageAndForward",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rescue_transfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransferTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTo",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveMessageAndForward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescue_transfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setManager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTransferTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transferTo", data: BytesLike): Result;
}

export namespace AdminUpdatedEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerUpdatedEvent {
  export type InputTuple = [oldManager: AddressLike, newManager: AddressLike];
  export type OutputTuple = [oldManager: string, newManager: string];
  export interface OutputObject {
    oldManager: string;
    newManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageReceivedAndForwardedEvent {
  export type InputTuple = [
    caller: AddressLike,
    messageTransmitter: AddressLike,
    token: AddressLike,
    forwardedAmount: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    messageTransmitter: string,
    token: string,
    forwardedAmount: bigint
  ];
  export interface OutputObject {
    caller: string;
    messageTransmitter: string;
    token: string;
    forwardedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RescueTransferEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferToUpdatedEvent {
  export type InputTuple = [
    oldTransferTo: AddressLike,
    newTransferTo: AddressLike
  ];
  export type OutputTuple = [oldTransferTo: string, newTransferTo: string];
  export interface OutputObject {
    oldTransferTo: string;
    newTransferTo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EthCctpReceiveProxy extends BaseContract {
  connect(runner?: ContractRunner | null): EthCctpReceiveProxy;
  waitForDeployment(): Promise<this>;

  interface: EthCctpReceiveProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  manager: TypedContractMethod<[], [string], "view">;

  receiveMessageAndForward: TypedContractMethod<
    [
      messageTransmitter: AddressLike,
      token: AddressLike,
      message: BytesLike,
      attestation: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  rescue_transfer: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAdmin: TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;

  setManager: TypedContractMethod<
    [newManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setTransferTo: TypedContractMethod<
    [newTransferTo: AddressLike],
    [void],
    "nonpayable"
  >;

  transferTo: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "manager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiveMessageAndForward"
  ): TypedContractMethod<
    [
      messageTransmitter: AddressLike,
      token: AddressLike,
      message: BytesLike,
      attestation: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rescue_transfer"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setManager"
  ): TypedContractMethod<[newManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTransferTo"
  ): TypedContractMethod<[newTransferTo: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferTo"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AdminUpdated"
  ): TypedContractEvent<
    AdminUpdatedEvent.InputTuple,
    AdminUpdatedEvent.OutputTuple,
    AdminUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ManagerUpdated"
  ): TypedContractEvent<
    ManagerUpdatedEvent.InputTuple,
    ManagerUpdatedEvent.OutputTuple,
    ManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MessageReceivedAndForwarded"
  ): TypedContractEvent<
    MessageReceivedAndForwardedEvent.InputTuple,
    MessageReceivedAndForwardedEvent.OutputTuple,
    MessageReceivedAndForwardedEvent.OutputObject
  >;
  getEvent(
    key: "RescueTransfer"
  ): TypedContractEvent<
    RescueTransferEvent.InputTuple,
    RescueTransferEvent.OutputTuple,
    RescueTransferEvent.OutputObject
  >;
  getEvent(
    key: "TransferToUpdated"
  ): TypedContractEvent<
    TransferToUpdatedEvent.InputTuple,
    TransferToUpdatedEvent.OutputTuple,
    TransferToUpdatedEvent.OutputObject
  >;

  filters: {
    "AdminUpdated(address,address)": TypedContractEvent<
      AdminUpdatedEvent.InputTuple,
      AdminUpdatedEvent.OutputTuple,
      AdminUpdatedEvent.OutputObject
    >;
    AdminUpdated: TypedContractEvent<
      AdminUpdatedEvent.InputTuple,
      AdminUpdatedEvent.OutputTuple,
      AdminUpdatedEvent.OutputObject
    >;

    "ManagerUpdated(address,address)": TypedContractEvent<
      ManagerUpdatedEvent.InputTuple,
      ManagerUpdatedEvent.OutputTuple,
      ManagerUpdatedEvent.OutputObject
    >;
    ManagerUpdated: TypedContractEvent<
      ManagerUpdatedEvent.InputTuple,
      ManagerUpdatedEvent.OutputTuple,
      ManagerUpdatedEvent.OutputObject
    >;

    "MessageReceivedAndForwarded(address,address,address,uint256)": TypedContractEvent<
      MessageReceivedAndForwardedEvent.InputTuple,
      MessageReceivedAndForwardedEvent.OutputTuple,
      MessageReceivedAndForwardedEvent.OutputObject
    >;
    MessageReceivedAndForwarded: TypedContractEvent<
      MessageReceivedAndForwardedEvent.InputTuple,
      MessageReceivedAndForwardedEvent.OutputTuple,
      MessageReceivedAndForwardedEvent.OutputObject
    >;

    "RescueTransfer(address,address,uint256)": TypedContractEvent<
      RescueTransferEvent.InputTuple,
      RescueTransferEvent.OutputTuple,
      RescueTransferEvent.OutputObject
    >;
    RescueTransfer: TypedContractEvent<
      RescueTransferEvent.InputTuple,
      RescueTransferEvent.OutputTuple,
      RescueTransferEvent.OutputObject
    >;

    "TransferToUpdated(address,address)": TypedContractEvent<
      TransferToUpdatedEvent.InputTuple,
      TransferToUpdatedEvent.OutputTuple,
      TransferToUpdatedEvent.OutputObject
    >;
    TransferToUpdated: TypedContractEvent<
      TransferToUpdatedEvent.InputTuple,
      TransferToUpdatedEvent.OutputTuple,
      TransferToUpdatedEvent.OutputObject
    >;
  };
}
