/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EthCctpReceiveProxy } from "./EthCctpReceiveProxy";
export type { IERC20 } from "./IERC20";
export type { IMessageTransmitter } from "./IMessageTransmitter";
